name: "Multi Event Pipeline/WorkFlow"
on:
  push: # Event: whenever the push is made to the repository on the master/test branch
    branches:
      - master
      - test
  
  pull_request: # Event: Whenever a pull request is made to the repository
    branches:
      - master
    types:
      - closed  
  workflow_dispatch: # Event: whenever a workflow is manually triggered 

jobs:
  on-push:  # job name 1nd job
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:  # steps to be executed on the job
      - name: "Running on master/test push"
        run: echo "running on master/test branch"

  on-pull-request: # job name 2nd job
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps: # steps to be executed on pull req in the job
      - name: "Running on pull request"
        run: echo "running on pull request"

  on-pull-request-closed: 
    if: github.event.name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    steps: 
      - name: "Running on pull request closed"
        run: echo "running on pull request closed"      

  workflow_dispatch: # # This enables manual triggering job 3
    if: github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    steps: 
     - name: "Running the workflow dispatch"
       run: echo "Running WorkFlow Dispatch"