name: "Multi Event Pipeline/WorkFlow"
on:
  push: # Event: whenever the push is made to the repository on the master/test branch
    branches:
      - master
      - test
  
  pull_request: # Event: Whenever a pull request is made to the repository
    branches:
     - master
jobs:
  on-push:  # job name
    runs-on: ubuntu-latest
    steps:  # steps to be executed on the job
      - name: "Running on master/test push"
        run: echo "running on master/test branch"

  on-pull-request: # job name
    runs-on: ubuntu-latest
    steps: # steps to be executed on pull req in the job
      - name: "Running on pull request"
        run:  echo "running on pull request"     