name: "Multi Event Pipeline/WorkFlow"
on:
  push: # Event: whenever the push is made to the repository on the master/test branch
    branches:
      - master
      - test

  schedule:
    - corn: "0.10 * * 2,4" # Event: every Tuesday and thursday at 10 AM

  pull_request: # Event: Whenever a pull request is made to the repository
    branches:
      - master
    types:
      - closed  
  
  workflow_dispatch: # Event: whenever a workflow is manually triggered 

jobs:
  on-push:  # job name 1st job
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:  # steps to be executed on the job
      - name: "Running on master/test push"
        run: echo "running on master/test branch"

  on-pull-request: # job name 2nd job
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps: # steps to be executed on pull req in the job
      - name: "Running on pull request"
        run: echo "running on pull request"

  on-pull-request-closed: # job name 3rd job
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    steps: 
      - name: "Running on pull request closed"
        run: echo "running on pull request closed"      

  workflow-dispatch: # job name 4th job - This enables manual triggering
    if: github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    steps: 
      - name: "Running the workflow dispatch"
        run: echo "Running WorkFlow Dispatch"

  on-schedule: 
    runs-on: ubuntu-latest
    steps:
      - name: "Running on Schedule"
        run: echo "running on"      